### ISSUE TITLE
Can I change the detector to yolov7 or other?

### ISSUE THREAD

**Issue by spoon0525** [regob/vehicle_mtmc#6]
please tell me which file I need to change, so I can use yolov7 as the devector

**Comment by regob** [comment]
Hi!

The detector is loaded in [load_detector.py](https://github.com/regob/vehicle_mtmc/blob/master/detection/load_detector.py).
This uses the yolov5 repo, so I guess you could add loading yolov7 here if the DETECTOR config parameter is e.g. 'yolov7'

Detection is happening [here](https://github.com/regob/vehicle_mtmc/blob/39c2f2fe1f623d28783c29a3b8c5822efa9467dc/mot/run_tracker.py#L227), so if your detector has a different API, this has to be changed.

**Comment by spoon0525** [comment]
understand, thank you very much!
